### ISSUE TITLE
Chinese (Traditional) untranslated line

### ISSUE THREAD

**Issue by EV1LG0D** [microsoft/vscode-loc#395] opened 2021-08-06 10:42 UTC
See my picture, when you right click on code area, "find all reference" should changed to " 尋找所有參考"
![圖片](https://user-images.githubusercontent.com/18423666/128498287-6c73651f-ba04-45ca-beb5-44bdb4114984.png)

**Comment by v-mholloway** [comment] 2021-08-16 13:29
@EV1LG0D can you provide more information as to how you reproduce this issue?

Note: all occurrences of that string in vscode, dev16 & dev17 Fabric translations are localized.
could the issue be further downstream?

**Comment by EV1LG0D** [comment] 2021-08-20 14:38
> 
> 
> @EV1LG0D can you provide more information as to how you reproduce this issue?
> 
> Note: all occurrences of that string in vscode, dev16 & dev17 Fabric translations are localized.
> could the issue be further downstream?
just right click on code line.

**Comment by EV1LG0D** [comment] 2021-08-20 14:38
> 
> 
> @EV1LG0D can you provide more information as to how you reproduce this issue?
> 
> Note: all occurrences of that string in vscode, dev16 & dev17 Fabric translations are localized.
> could the issue be further downstream?

just right click on code line.

**Comment by v-mholloway** [comment] 2021-09-01 14:29
closing this as a duplicate of https://github.com/microsoft/vscode-loc/issues/427

**Closed by v-mholloway** 2021-09-01 14:29 UTC
Labels: L10N
