### ISSUE TITLE
今天更新后 GitLens 就不汉化了，谢谢贡献者。

### ISSUE THREAD

**Issue by Ade-Li** [microsoft/vscode-loc#1159] opened 2022-11-10 07:34 UTC
![1668065535301](https://user-images.githubusercontent.com/67159054/201027880-65a31c6d-2055-45f4-9c42-04fc6194842b.png)

**Comment by vic233333** [comment] 2022-11-11 14:29
same bug, sad from china

**Comment by MasterEw** [comment] 2022-11-12 00:42
same bug

**Comment by kaoding** [comment] 2022-11-12 01:32
same bug

**Comment by kaoding** [comment] 2022-11-12 01:32
same bug

**Comment by csigs** [comment] 2022-11-12 02:26
Thank you for your feedback. We are currently reviewing it (reference 740850).

**Comment by Tanimodori** [comment] 2022-11-14 01:59
Same bug confirmed. The installed version is v1.73.11090913

**Comment by Last-Order-Wsk** [comment] 2022-11-14 06:48
> same bug **关闭扩展的自动更新！** 卸载插件，用VSIX的方式重新安装v1.73.11020948版本后，解决问题。

link here [link](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans)

**Comment by translateServers** [comment] 2022-11-14 08:11
Thank you very much

**Comment by v-mholloway** [comment] 2022-11-14 16:19
@Ade-Li can you specify in english exactly what the problem is...?

is the specific problem here that alot of the dialog is in not translated...?

**Comment by vic233333** [comment] 2022-11-14 16:55
> @Ade-Li can you specify in english exactly what the problem is...?
> 
> is the specific problem here that alot of the dialog is in not translated...?

@v-mholloway 
Yes. some of the translation is missing in v1.73.11090913
You can see the difference between the previous version (v1.73.11020948) and the latest version (v1.73.11090913) in the following screen shoot.
![未标题-1](https://user-images.githubusercontent.com/93087330/201719006-f2e1172f-e526-49bd-82c0-84df9a32b9d5.png)

**Comment by crsuzukimsft** [comment] 2022-11-17 21:41
Hi @TylerLeonhardt could you check on this one? The translations seem to be reverted at the mentioned build number.

**Comment by crsuzukimsft** [comment] 2022-11-30 18:42
@TylerLeonhardt I think this is related to https://github.com/microsoft/vscode/issues/165974.

**Comment by TylerLeonhardt** [comment] 2022-12-07 19:38
Yes it's a duplicate of that one. Fixed in the new vscode going out this week.

**Closed by TylerLeonhardt** 2022-12-07 19:38 UTC
