### ISSUE TITLE
[zh-cn]连接到wsl后部分中文变回英文

### ISSUE THREAD

**Issue by Mobius0526** [microsoft/vscode-loc#1744] opened 2024-11-22 02:33 UTC
![Image](https://github.com/user-attachments/assets/c1360bc6-7d7d-42c9-bda6-3b5cf591d707)

**Comment by csigs** [comment] 2024-11-25 02:24
Thank you for your feedback. We will review the issue (ICX ADO Tracking Reference: 1014836).

**Comment by cristianosuzuki77** [comment] 2024-12-02 22:00
@TylerLeonhardt could I run this through you first? it says strings reverted to EN after connecting to wsl. Not sure if this is a runtime issue.

**Comment by TylerLeonhardt** [comment] 2024-12-03 08:41
This is actually a duplicate of https://github.com/microsoft/vscode/issues/151000

**Closed by TylerLeonhardt** 2024-12-03 08:41 UTC
