### ISSUE TITLE
The internationalization of some extensions has failed, such as git's simplified Chinese

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode-loc#1157] opened 2022-11-10 06:41 UTC
![](https://user-images.githubusercontent.com/6134547/200992223-f09e4224-e76f-4b62-bb05-6caca591739a.png)

Maybe related:

![image](https://user-images.githubusercontent.com/11473889/201016300-99a189c2-d513-4616-bb5a-1c6870ac1b8a.png)

There is no translation here, it is all the default English.

 [vscode.git.i18n.json](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/extensions/vscode.git.i18n.json)

**Comment by yiliang114** [comment] 2022-11-10 06:42
related [165974](https://github.com/microsoft/vscode/issues/165974)

**Comment by NatureLR** [comment] 2022-11-10 06:44
me too

**Comment by ihola777** [comment] 2022-11-10 07:16
same issue here #165983

**Comment by TylerLeonhardt** [comment] 2022-11-10 17:07
/duplicate https://github.com/microsoft/vscode/issues/165974#issuecomment-1310465539

**Comment by TylerLeonhardt** [comment] 2022-11-10 17:07
This is a duplicate of https://github.com/microsoft/vscode/issues/165974#issuecomment-1310465539 and there's a workaround in that thread.

**Closed by TylerLeonhardt** 2022-11-10 17:07 UTC
