### ISSUE TITLE
Some notebook commands will be invisible when using Chinese (Simplified)

### ISSUE THREAD

**Issue by ganxy1028** [microsoft/vscode-loc#941] opened 2022-07-08 02:42 UTC
Version: 1.69.0 (user setup)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

With the newest stable version of vscode, some notebook commands on the top will be invisible when using Chinese (Simplified), while it runs well if the language extension is uninstalled. 
Is it a vscode / vscode-loc / jupyter problem?

![image](https://user-images.githubusercontent.com/26629457/177907986-56a0f4f1-5244-48b7-b1a0-e9efc438fb5d.png)

![image](https://user-images.githubusercontent.com/26629457/177906663-a1ab2600-cd5b-40f8-b478-c35eb025f6cc.png)

**Comment by csigs** [comment] 2022-07-08 09:28
Thank you for your feedback. We are currently reviewing it (reference 655744).

**Comment by cristianosuzuki77** [comment] 2022-07-15 22:06
@TylerLeonhardt  could you review this ticket? I'm not clear if this is loc or not.

**Comment by TylerLeonhardt** [comment] 2022-07-16 00:41
Hi @ganxy1028, sorry for this. This is a duplicate of https://github.com/microsoft/vscode/issues/154955 and the fix will be in the next major version 1.70 released early next month.

In the meantime you can use the latest insider build of VS Code which has the fix: http://code.visualstudio.com/insiders

**Closed** 2022-07-16 00:41 UTC
