### ISSUE TITLE
安装后不显示 Copilot chat 图标选项

### ISSUE THREAD

**Issue by XiaoLiz** [microsoft/vscode-loc#1462] opened 2023-08-07 08:10 UTC
Type: <b>Bug</b>

安装后不显示 Copilot chat 图标选项

Extension version: 1.81.2023080209
VS Code version: Code 1.81.0 (Universal) (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin arm64 21.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id f621a728-c227-442c-b6a4-c443a10149af|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by csigs** [comment] 2023-08-07 09:24
Thank you for your feedback. We are currently reviewing it (reference 879873).

**Comment by csigs** [comment] 2023-08-08 01:24
Investigated by Loc Team: It's not a translation issue. (Reference id: 879873)

**Comment by csigs** [comment] 2023-09-07 01:24
Thank you for your feedback. We are currently reviewing it (reference 896966).

**Comment by v-mholloway** [comment] 2023-09-07 11:18
@XiaoLiz can you please describe what the issue is...?

**Comment by v-mholloway** [comment] 2023-09-19 14:23
closing as we require more information and this does not appear to be a Loc issue.. please open new issue with additional info if you still require a change to be implemented.

**Closed** 2023-09-19 14:23 UTC
Labels: info-needed
