### ISSUE TITLE
Certain Remote Repositories commands not translated

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-loc#922] opened 2022-06-28 15:55 UTC
Testing https://github.com/microsoft/vscode/issues/153391 with Firefox set to Spanish.

- Open Remote Explorer
- Switch to Remote Repositories tab, select button to open a remote repo
- Commands are in English, although the button and Remote Explorer text were in Spanish:

![image](https://user-images.githubusercontent.com/25310137/176224858-60b3a1bd-d51c-4bb7-85c3-61bd894d6084.png)

- If I search for Remote Repositories commands in the command palette on my own, the commands are translated:

![image](https://user-images.githubusercontent.com/25310137/176225095-25722623-691e-4147-809b-ac7d9efe1306.png)

**Comment by TylerLeonhardt** [comment] 2022-06-28 16:09
This is because it comes from the code:
https://github.com/microsoft/vscode-remotehub/blob/2af954ea19ed2bc1758ad305f21e548cac8c62c5/extensions/azurerepos/src/provider.ts#L276

and I haven't supported that yet. Closing this since it's working "as designed" for now. Next milestone will have the feature work that should enable this.

**Closed by TylerLeonhardt** 2022-06-28 16:09 UTC
