### ISSUE TITLE
Hopefully the language extension will run on vscode.dev

### ISSUE THREAD

**Issue by cws999** [microsoft/vscode-loc#864] opened 2022-05-19 14:28 UTC
Hopefully the language extension will run on vscode.dev and  cdr/code-server and gitpod-io/openvscode-server
https://code.visualstudio.com/api/extension-guides/web-extensions

I added the following code, but it still doesn't work.

`"activationEvents": [
    "*"
]`
`"browser": "./translations/main.i18n.json",`

please help me  please help me

**Comment by csigs** [comment] 2022-05-20 01:26
The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/611944.

**Comment by cws999** [comment] 2022-05-20 06:35
> The issue has been ported to ADO in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/611944.

Your account, xxxx@xxxxx.com is not authorized to view this page. Make sure the URL is correct and your account has access. View a list of your organizations [here](https://go.microsoft.com/fwlink/?LinkId=309329). You may request access by contacting the admin.

**Comment by crsuzukimsft** [comment] 2022-05-25 15:12
Hello,
could you explain further what is that you'd like to try out? 

Thank you

**Comment by cws999** [comment] 2022-05-30 17:54
@crsuzukimsft I hope to be able to install language extensions on the  " vscode.dev  or  openvscode-server  "  , Because my native language is not English

**Comment by cristianosuzuki77** [comment] 2022-06-29 22:08
@TylerLeonhardt Could you assist here?

**Comment by TylerLeonhardt** [comment] 2022-06-29 22:12
@cws999 have you used vscode.dev recently? If your browser is in a different language and is one of the languages we support you should see translations. Additionally, if you try insiders.vscode.dev you should be able to run the command `Configure Display Language` to set the language explicitly. I can't speak to code-server or OpenVSCodeServer since those are not owned by the VS Code team.

**Comment by TylerLeonhardt** [comment] 2022-06-29 22:15
I will close this as a duplicate of https://github.com/microsoft/vscode/issues/82595

**Closed by TylerLeonhardt** 2022-06-29 22:15 UTC
