### ISSUE TITLE
SCM Translate——Chinese Language Pack for Visual Studio Code v1.73.11090913

### ISSUE THREAD

**Issue by DragonsZhou** [microsoft/vscode-loc#1165] opened 2022-11-13 13:27 UTC
SCM cannot  be translated into Chinese
![image](https://user-images.githubusercontent.com/49547352/201524091-56f02780-fdd4-444e-926e-aef02e00d547.png)

**Comment by csigs** [comment] 2022-11-13 18:26
Thank you for your feedback. We are currently reviewing it (reference 741149).

**Comment by crsuzukimsft** [comment] 2022-11-14 23:04
Thank you, @DragonsZhou. Could you explain more about this feedback. It is not clear to me.

**Comment by Leslie1900** [comment] 2022-11-15 01:04
> Thank you, @DragonsZhou. Could you explain more about this feedback. It is not clear to me.

Version 1.73.11090913 cannot Chinese and localize the content of vscode source control。Thanks

**Comment by DragonsZhou** [comment] 2022-11-15 03:22
> Thank you, @DragonsZhou. Could you explain more about this feedback. It is not clear to me.


> > Thank you, @DragonsZhou. Could you explain more about this feedback. It is not clear to me.
> 
> Version 1.73.11090913 cannot Chinese and localize the content of vscode source control。Thanks


VSCode v1.73.11090913 can't Chineseize and localize the menu of SCM. 
![image](https://user-images.githubusercontent.com/49547352/201818758-579e9788-5464-4b01-b2ce-e063d982ced5.png)

I guess it's a problem with the Chinese language pack, so I changed the version of the Chinese language pack, but it still doesn't work. Then I changed the VSCode version again, still not working.
So I'm giving feedback on this issue here.

**Comment by inqbs** [comment] 2022-11-15 04:11
Same problem in korean too.
![capture](https://user-images.githubusercontent.com/52809869/201824475-aa8fe9bf-1a02-46b1-ae21-afd968b918a7.PNG)

**Comment by inqbs** [comment] 2022-11-16 00:46
Same issue here.
https://github.com/microsoft/vscode/issues/165974

**Comment by crsuzukimsft** [comment] 2022-11-30 18:39
Thanks, I see https://github.com/microsoft/vscode/issues/165974 addressed it.

**Comment by TylerLeonhardt** [comment] 2022-12-10 00:39
duplicate of https://github.com/microsoft/vscode/issues/165974 should be fixed now

**Closed by TylerLeonhardt** 2022-12-10 00:39 UTC
